### ISSUE TITLE
[Feature Request]: Chrome Refresh 2023

### ISSUE THREAD

**Issue by IlIllIl** [edelvarden/material-fox-updated#21]
### Description

The newer chrome style looks like:
<img width="937" alt="image" src="https://github.com/edelvarden/material-fox-updated/assets/99599914/3a858628-dafa-4324-90d2-b4accb84a3fe">

### Additional info (Optional)

Firefox version:  118.0.1
Operating system: macOS

**Comment by edelvarden** [comment]
Please provide more information regarding the specific features or changes, it will help me don't miss something and better understand your request.
Format like a list if there are multiple things. 
Also keep in mind Firefox theme looks similar to Chrome, and not 100% the same and not pixel perfect or something like that.

**Comment by IlIllIl** [comment]
As you see, there are more Material You elements:
- Accent Color
- Rounded-corner Button
<img width="180" alt="9748EE90-A950-4516-A449-30DCEDC437B5" src="https://github.com/edelvarden/material-fox-updated/assets/99599914/d604def1-a3ed-4763-abc8-f06692de077c">

- More Rounded-corner Elements
<img width="720" alt="image" src="https://github.com/edelvarden/material-fox-updated/assets/99599914/90baaba8-7d3d-42cd-b5b0-b0d9a401d5b1">

How can I make the shadow of the expanded address bar smaller, lighter?

<img width="180" alt="B2DCBBD7-AB8F-4C19-9708-0F18EA49C25A" src="https://github.com/edelvarden/material-fox-updated/assets/99599914/09f3dd06-fc61-4629-b927-813a136542c4">

How can I adjust the spacing? Could you give me some tips?

**Comment by edelvarden** [comment]
Did you see `userChrome.chrome-refresh-2023` param for `about:config`, this is implemented "Chrome Refresh 2023", I make it optional because users maybe prefer for current UI version, try it if you don't see (check readme for more info).

About "Accent Color" on the background and buttons, it possible to implement.

About "How can I make the shadow of the expanded address bar smaller, lighter?":
  1. Rename `custom-chrome_example.css` to `custom-chrome.css`.
  2. Open file and add: 
  
  ```css
  :root,
  html,
  body {
    /* add your css below */
    --mf-elevation-3: rgba(149, 157, 165, 0.2) 0px 8px 24px !important;
  }
  ```

3. Save file and restart Firefox.

You can use your own value, values can be found [here](https://getcssscan.com/css-box-shadow-examples)

About "How can I adjust the spacing? Could you give me some tips?":

In the same file add below:

  ```css
  :root,
  html,
  body {
    /* add your css below */
    --mf-elevation-3: rgba(149, 157, 165, 0.2) 0px 8px 24px !important;
  }
  
  .titlebar-buttonbox-container {
    margin-inline-end: 12px !important;
    }
  ```
  
  Change **12px** with your own.

**Comment by IlIllIl** [comment]
Wow, nice. Thanks for your reply.
The `userChrome.chrome-refresh-2023` in `about:config` looks not good now.
Can I adjust the spacing of them as well?
<img width="102" alt="image" src="https://github.com/edelvarden/material-fox-updated/assets/24961267/ef3c83a0-407f-4562-9863-2b7e7d5a0e39">
<img width="102" alt="image" src="https://github.com/edelvarden/material-fox-updated/assets/24961267/a6f04115-8c66-4550-a566-cec90b6e747c">

**Comment by edelvarden** [comment]
> Wow, nice. Thanks for your reply. The `userChrome.chrome-refresh-2023` in `about:config` looks not good now. Can I adjust the spacing of them as well? <img alt="image" width="102" src="https://user-images.githubusercontent.com/24961267/277124592-ef3c83a0-407f-4562-9863-2b7e7d5a0e39.png"> <img alt="image" width="102" src="https://user-images.githubusercontent.com/24961267/277124616-a6f04115-8c66-4550-a566-cec90b6e747c.png">

Try adding the following css param:

```css
:root,
html,
body {
--toolbarbutton-outer-padding: 3px !important;
}
```

Change **3px** with your own.

P.S. I don't know why you are trying achieve pixel perfection, because it can change over time and general styles looks good for me and I don't see any critical parts that need to be replaced, but I respect your preferences, if you want do this you can do this.

Provide any other remarks, if any.

**Comment by IlIllIl** [comment]
Thanks you :)
