### ISSUE TITLE
[Feature Request]: Custom home page or better search bar

### ISSUE THREAD

**Issue by NGSpace** [edelvarden/material-fox-updated#45]
### Description

The firefox search bar never really felt right for me, feels crowded and ugly. 

### Additional info (Optional)

Firefox version: 124.0.2
Operating system: Windows 11

**Comment by edelvarden** [comment]
Find bar has already been redesigned, I also can't understand you if you said "never really felt right for me" or "feels crowded and ugly", how I have to understand what I should do, please provide your design or describe more specifically.

**Comment by NGSpace** [comment]
I was talking about the newtab page's search bar. not the address-bar.

**Comment by edelvarden** [comment]
This does not cancel the fact that I need to understand what exactly you want.

**Comment by NGSpace** [comment]
Change the search-bar to something like this:

![image](https://github.com/edelvarden/material-fox-updated/assets/71827944/1da086a6-7d95-452f-b0ea-e56026a8c16a)

**Comment by NGSpace** [comment]
Change the search-bar to something like this:
![image](https://github.com/edelvarden/material-fox-updated/assets/71827944/88900cf2-c022-45f6-87de-325d06579eb5)

**Comment by edelvarden** [comment]
It is impossible, because Firefox use a fake search bar, any search request goes to the address line. I recommend use [New Tab Override](https://addons.mozilla.org/en-US/firefox/addon/new-tab-override/) extension and switch the home page to google.com
![image](https://github.com/edelvarden/material-fox-updated/assets/42596339/7816b787-2d70-44aa-b4c0-d50d911fc511)
