### ISSUE TITLE
[Bug]: Tab Hover Tooltip/Image bugged

### ISSUE THREAD

**Issue by danialasghar** [edelvarden/material-fox-updated#66]
### What happened?

There is a second placeholder animating into the tab hover tooltip/tab image as can be seen here:
![image](https://github.com/user-attachments/assets/7bcd6ff8-c88b-4036-987f-d2786d554102)

### Steps to reproduce

Hover over a tab
See the tooltip show
Then the second frame animates in

**Comment by edelvarden** [comment]
@danialasghar , I know about this, but you forgot to mention that it's only in the **nightly** version. As a temporary solution, you can use the following code:


```css
.tabbrowser-tab::after {
  display: none !important;
}
```

I add fixes only when it comes to the stable or dev version, because some features can be removed or not included, so there’s no point in adding fixes for those.

**Comment by danialasghar** [comment]
Ahh I realized what is happening. 

I am not using dev but I did force enable the tab hover preview using about:config. Disabling it fixed the issue. 

Thanks!

**Comment by edelvarden** [comment]
@danialasghar , added compatibility with the `browser.tabs.hoverPreview.enabled`. Now, when you enable it, the second tooltip is not displayed.
